//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanosCOMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ShoppingCartDetails = new HashSet<ShoppingCartDetail>();
            this.Taxes = new HashSet<Tax>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public double ProductPrice { get; set; }
        public int CategoryID { get; set; }
        public int SupplierID { get; set; }
        public int UnitsInStock { get; set; }
        public int ShippingID { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Shipping Shipping { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<ShoppingCartDetail> ShoppingCartDetails { get; set; }
        public virtual ICollection<Tax> Taxes { get; set; }
    }
}
