//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanosCOMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public Shipping()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ShippingID { get; set; }
        public string ShippingName { get; set; }
        public string ShippingTelephone { get; set; }
        public string ShippingHomePage { get; set; }
        public double ShippingTax { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
